const DummyData = {
  /***************** row 1 ************************/
  1: {
    id: 1,
    name: "San Francisco",
    subtitle: "My favorite resturaunts",
    tags: ["Chinese", "Moroccan", "Japanese", "Italian", "Tapas", "Wine bar"],
    visibility: "Public",
    bookmarks: "15",
    photo: "https://i.ibb.co/sR6cvst/Screen-Shot-2023-05-03-at-9-16-24-PM.png",
  },
  2: {
    id: 2,
    name: "New York",
    subtitle: "The Best Dining in NY",
    tags: [
      "Steak House",
      "speakeasy",
      "bar",
      "night",
      "club",
      "jazz",
      "bar",
      "fine dining",
    ],
    visibility: "Private",
    bookmarks: "32",
    photo: "https://i.ibb.co/XLZwrMC/new-york.png",
  },
  3: {
    id: 3,
    name: "Sushi",
    subtitle: "My fav sushi restaurants",
    tags: ["Must-visit", "cheap", "date night", "yummy"],
    visibility: "Private",
    bookmarks: "17",
    photo: "https://i.ibb.co/M5s4vZj/Screen-Shot-2023-05-04-at-12-53-32-AM.png",
  },
  4: {
    id: 4,
    name: "Cafe",
    subtitle: "The Best Dining in NY",
    tags: [
      "Matcha latte",
      "latte art",
      "croissant",
      "cold brew",
      "loose tea leaves",
    ],
    visibility: "Public",
    bookmarks: "21",
    photo: "https://i.ibb.co/KsPLxWN/Screen-Shot-2023-05-04-at-12-55-46-AM.png",
  },

  /***************** row 2 ************************/
  5: {
    id: 5,
    name: "Fuji Rolls",
    subtitle: "Fresh Sushi Rolls",
    tags: [
      "Sushi",
      "Japanese",
      "Seafood",
      "Healthy",
      "Casual",
      "Dine-in",
      "Takeout",
    ],
    visibility: "Private",
    bookmarks: "42",
    photo: "https://i.ibb.co/k9XHPNN/Screen-Shot-2023-05-04-at-12-55-51-AM.png",
  },
  6: {
    id: 6,
    name: "Bella Vita",
    subtitle: "Authentic Italian Cuisine",
    tags: [
      "Italian",
      "Pasta",
      "Pizza",
      "Wine",
      "Fine Dining",
      "Takeout",
      "Delivery",
    ],
    visibility: "Private",
    bookmarks: "18",
    photo: "https://i.ibb.co/cwWpQp3/Screen-Shot-2023-05-04-at-12-56-00-AM.png",
  },
  7: {
    id: 7,
    name: "Le Jardin",
    subtitle: "Authentic French Cuisine",
    tags: [
      "French",
      "Fine Dining",
      "Wine Bar",
      "Brunch",
      "Lunch",
      "Dinner",
    ],
    visibility: "Private",
    bookmarks: "22",
    photo: "https://i.ibb.co/mzqYW4T/Screen-Shot-2023-05-04-at-12-56-07-AM.png",
  },
  8: {
    id: 8,
    name: "El Ranchito",
    subtitle: "Authentic Mexican Cuisine",
    tags: [
      "Mexican",
      "Tacos",
      "Burritos",
      "Enchiladas",
      "Salsa",
      "Guacamole",

    ],
    visibility: "Private",
    bookmarks: "10",
    photo: "https://i.ibb.co/g40vrJJ/Screen-Shot-2023-05-04-at-12-55-35-AM.png",
  },
};

const DummyData2 = {
    /***************** row 1 ************************/

    1: {
      id: 2,
      name: "New York",
      subtitle: "The Best Dining in NY",
      tags: [
        "Steak House",
        "speakeasy",
        "bar",
        "night",
        "club",
        "jazz",
        "bar",
        "fine dining",
      ],
      user: "Arielle",
      pfp: "https://i.ibb.co/FzpQcNT/33986-F7-C-DCA5-418-C-ACB9-917-CCB6-E5094.jpg",
      bookmarks: "32",
      photo: "https://i.ibb.co/XLZwrMC/new-york.png",
    },
    2: {
        id: 1,
        name: "San Francisco",
        subtitle: "My favorite resturaunts",
        tags: ["Chinese", "Moroccan", "Japanese", "Italian", "Tapas", "Wine bar"],
        user: "Marcel",
        pfp: "https://i.ibb.co/cDwSBHk/8-C5-BA17-C-326-E-4-C48-AE3-E-70-B3-D33-CE024.jpg",
        bookmarks: "15",
        photo: "https://i.ibb.co/sR6cvst/Screen-Shot-2023-05-03-at-9-16-24-PM.png",
      },
    3: {
      id: 4,
      name: "Cafe",
      subtitle: "The Best Dining in NY",
      tags: [
        "Matcha latte",
        "latte art",
        "croissant",
        "cold brew",
        "loose tea leaves",
      ],
      user: "Marcel",
        pfp: "https://i.ibb.co/cDwSBHk/8-C5-BA17-C-326-E-4-C48-AE3-E-70-B3-D33-CE024.jpg",
      bookmarks: "21",
      photo: "https://i.ibb.co/KsPLxWN/Screen-Shot-2023-05-04-at-12-55-46-AM.png",
    },
  
    /***************** row 2 ************************/
    4: {
      id: 5,
      name: "Fuji Rolls",
      subtitle: "Fresh Sushi Rolls",
      tags: [
        "Sushi",
        "Japanese",
        "Seafood",
        "Healthy",
        "Casual",
        "Dine-in",
        "Takeout",
      ],
      user: "Arielle",
      pfp: "https://i.ibb.co/FzpQcNT/33986-F7-C-DCA5-418-C-ACB9-917-CCB6-E5094.jpg",
      bookmarks: "42",
      photo: "https://i.ibb.co/k9XHPNN/Screen-Shot-2023-05-04-at-12-55-51-AM.png",
    },
    5: {
        id: 3,
        name: "Sushi",
        subtitle: "My fav sushi restaurants",
        tags: ["Must-visit", "cheap", "date night", "yummy"],
        user: "Arielle",
      pfp: "https://i.ibb.co/FzpQcNT/33986-F7-C-DCA5-418-C-ACB9-917-CCB6-E5094.jpg",
        bookmarks: "17",
        photo: "https://i.ibb.co/M5s4vZj/Screen-Shot-2023-05-04-at-12-53-32-AM.png",
      },
    6: {
      id: 6,
      name: "Bella Vita",
      subtitle: "Authentic Italian Cuisine",
      tags: [
        "Italian",
        "Pasta",
        "Pizza",
        "Wine",
        "Fine Dining",
        "Takeout",
        "Delivery",
      ],
      user: "Marcel",
        pfp: "https://i.ibb.co/cDwSBHk/8-C5-BA17-C-326-E-4-C48-AE3-E-70-B3-D33-CE024.jpg",
      bookmarks: "18",
      photo: "https://i.ibb.co/cwWpQp3/Screen-Shot-2023-05-04-at-12-56-00-AM.png",
    },
    7: {
      id: 8,
      name: "El Ranchito",
      subtitle: "Authentic Mexican Cuisine",
      tags: [
        "Mexican",
        "Tacos",
        "Burritos",
        "Enchiladas",
        "Salsa",
        "Guacamole",
  
      ],
      user: "Marcel",
        pfp: "https://i.ibb.co/cDwSBHk/8-C5-BA17-C-326-E-4-C48-AE3-E-70-B3-D33-CE024.jpg",
      bookmarks: "10",
      photo: "https://i.ibb.co/g40vrJJ/Screen-Shot-2023-05-04-at-12-55-35-AM.png",
    },
    8: {
        id: 7,
        name: "Le Jardin",
        subtitle: "Authentic French Cuisine",
        tags: [
          "French",
          "Fine Dining",
          "Wine Bar",
          "Brunch",
          "Lunch",
          "Dinner",
        ],
        user: "Arielle",
      pfp: "https://i.ibb.co/FzpQcNT/33986-F7-C-DCA5-418-C-ACB9-917-CCB6-E5094.jpg",
        bookmarks: "22",
        photo: "https://i.ibb.co/mzqYW4T/Screen-Shot-2023-05-04-at-12-56-07-AM.png",
      },
  };


const DummyData4= {
    /***************** row 1 ************************/
    1: {
      id: 2,
      name: "New York",
      subtitle: "The Best Dining in NY",
      tags: [
        "Steak House",
        "speakeasy",
        "bar",
        "night",
        "club",
        "jazz",
        "bar",
        "fine dining",
      ],
      user: "Arielle",
      pfp: "https://i.ibb.co/FzpQcNT/33986-F7-C-DCA5-418-C-ACB9-917-CCB6-E5094.jpg",
      bookmarks: "32",
      photo: "https://i.ibb.co/XLZwrMC/new-york.png",
    },
    2: {
      id: 4,
      name: "Cafe",
      subtitle: "The Best Dining in NY",
      tags: [
        "Matcha latte",
        "latte art",
        "croissant",
        "cold brew",
        "loose tea leaves",
      ],
      user: "Marcel",
        pfp: "https://i.ibb.co/cDwSBHk/8-C5-BA17-C-326-E-4-C48-AE3-E-70-B3-D33-CE024.jpg",
      bookmarks: "21",
      photo: "https://i.ibb.co/KsPLxWN/Screen-Shot-2023-05-04-at-12-55-46-AM.png",
    },
  
    /***************** row 2 ************************/
    3: {
      id: 6,
      name: "Bella Vita",
      subtitle: "Authentic Italian Cuisine",
      tags: [
        "Italian",
        "Pasta",
        "Pizza",
        "Wine",
        "Fine Dining",
        "Takeout",
        "Delivery",
      ],
      user: "Marcel",
        pfp: "https://i.ibb.co/cDwSBHk/8-C5-BA17-C-326-E-4-C48-AE3-E-70-B3-D33-CE024.jpg",
      bookmarks: "18",
      photo: "https://i.ibb.co/cwWpQp3/Screen-Shot-2023-05-04-at-12-56-00-AM.png",
    },
    4: {
      id: 7,
      name: "Le Jardin",
      subtitle: "Authentic French Cuisine",
      tags: [
        "French",
        "Fine Dining",
        "Wine Bar",
        "Brunch",
        "Lunch",
        "Dinner",
      ],
      user: "Arielle",
      pfp: "https://i.ibb.co/FzpQcNT/33986-F7-C-DCA5-418-C-ACB9-917-CCB6-E5094.jpg",
      bookmarks: "22",
      photo: "https://i.ibb.co/mzqYW4T/Screen-Shot-2023-05-04-at-12-56-07-AM.png",
    },
    5: {
      id: 8,
      name: "El Ranchito",
      subtitle: "Authentic Mexican Cuisine",
      tags: [
        "Mexican",
        "Tacos",
        "Burritos",
        "Enchiladas",
        "Salsa",
        "Guacamole",
  
      ],
      user: "Marcel",
        pfp: "https://i.ibb.co/cDwSBHk/8-C5-BA17-C-326-E-4-C48-AE3-E-70-B3-D33-CE024.jpg",
      bookmarks: "10",
      photo: "https://i.ibb.co/g40vrJJ/Screen-Shot-2023-05-04-at-12-55-35-AM.png",
    },
  };

  
const DummyData3 = {
    /***************** row 1 ************************/

    1: {
        id: 4,
        name: "Cafe",
        subtitle: "The Best Dining in NY",
        tags: [
          "Matcha latte",
          "latte art",
          "croissant",
          "cold brew",
          "loose tea leaves",
        ],
        user: "Marcel",
        pfp: "https://i.ibb.co/cDwSBHk/8-C5-BA17-C-326-E-4-C48-AE3-E-70-B3-D33-CE024.jpg",
        bookmarks: "21",
        photo: "https://i.ibb.co/KsPLxWN/Screen-Shot-2023-05-04-at-12-55-46-AM.png",
      },
    2: {
      id: 2,
      name: "New York",
      subtitle: "The Best Dining in NY",
      tags: [
        "Steak House",
        "speakeasy",
        "bar",
        "night",
        "club",
        "jazz",
        "bar",
        "fine dining",
      ],
      user: "Arielle",
      pfp: "https://i.ibb.co/FzpQcNT/33986-F7-C-DCA5-418-C-ACB9-917-CCB6-E5094.jpg",
      bookmarks: "32",
      photo: "https://i.ibb.co/XLZwrMC/new-york.png",
    },
    3: {
        id: 1,
        name: "San Francisco",
        subtitle: "My favorite resturaunts",
        tags: ["Chinese", "Moroccan", "Japanese", "Italian", "Tapas", "Wine bar"],
        user: "Marcel",
        pfp: "https://i.ibb.co/cDwSBHk/8-C5-BA17-C-326-E-4-C48-AE3-E-70-B3-D33-CE024.jpg",
        bookmarks: "15",
        photo: "https://i.ibb.co/sR6cvst/Screen-Shot-2023-05-03-at-9-16-24-PM.png",
      },
  
    4: {
        id: 3,
        name: "Sushi",
        subtitle: "My fav sushi restaurants",
        tags: ["Must-visit", "cheap", "date night", "yummy"],
        user: "Arielle",
      pfp: "https://i.ibb.co/FzpQcNT/33986-F7-C-DCA5-418-C-ACB9-917-CCB6-E5094.jpg",
        bookmarks: "17",
        photo: "https://i.ibb.co/M5s4vZj/Screen-Shot-2023-05-04-at-12-53-32-AM.png",
      },
    5: {
      id: 6,
      name: "Bella Vita",
      subtitle: "Authentic Italian Cuisine",
      tags: [
        "Italian",
        "Pasta",
        "Pizza",
        "Wine",
        "Fine Dining",
        "Takeout",
        "Delivery",
      ],
      user: "Marcel",
        pfp: "https://i.ibb.co/cDwSBHk/8-C5-BA17-C-326-E-4-C48-AE3-E-70-B3-D33-CE024.jpg",
      bookmarks: "18",
      photo: "https://i.ibb.co/cwWpQp3/Screen-Shot-2023-05-04-at-12-56-00-AM.png",
    },
    6: {
        id: 7,
        name: "Le Jardin",
        subtitle: "Authentic French Cuisine",
        tags: [
          "French",
          "Fine Dining",
          "Wine Bar",
          "Brunch",
          "Lunch",
          "Dinner",
        ],
        user: "Arielle",
      pfp: "https://i.ibb.co/FzpQcNT/33986-F7-C-DCA5-418-C-ACB9-917-CCB6-E5094.jpg",
        bookmarks: "22",
        photo: "https://i.ibb.co/mzqYW4T/Screen-Shot-2023-05-04-at-12-56-07-AM.png",
      },
        /***************** row 2 ************************/
    7: {
      id: 5,
      name: "Fuji Rolls",
      subtitle: "Fresh Sushi Rolls",
      tags: [
        "Sushi",
        "Japanese",
        "Seafood",
        "Healthy",
        "Casual",
        "Dine-in",
        "Takeout",
      ],
      user: "Arielle",
      pfp: "https://i.ibb.co/FzpQcNT/33986-F7-C-DCA5-418-C-ACB9-917-CCB6-E5094.jpg",
      bookmarks: "42",
      photo: "https://i.ibb.co/k9XHPNN/Screen-Shot-2023-05-04-at-12-55-51-AM.png",
    },
    8: {
      id: 8,
      name: "El Ranchito",
      subtitle: "Authentic Mexican Cuisine",
      tags: [
        "Mexican",
        "Tacos",
        "Burritos",
        "Enchiladas",
        "Salsa",
        "Guacamole",
  
      ],
      user: "Marcel",
        pfp: "https://i.ibb.co/cDwSBHk/8-C5-BA17-C-326-E-4-C48-AE3-E-70-B3-D33-CE024.jpg",
      bookmarks: "10",
      photo: "https://i.ibb.co/g40vrJJ/Screen-Shot-2023-05-04-at-12-55-35-AM.png",
    },
  };

  const DummyData5 = {
    /***************** row 1 ************************/

    1: {
        id: 4,
        name: "Cafe",
        subtitle: "The Best Dining in NY",
        tags: [
          "Matcha latte",
          "latte art",
          "croissant",
          "cold brew",
          "loose tea leaves",
        ],
        user: "Marcel",
        pfp: "https://i.ibb.co/cDwSBHk/8-C5-BA17-C-326-E-4-C48-AE3-E-70-B3-D33-CE024.jpg",
        bookmarks: "21",
        photo: "https://i.ibb.co/KsPLxWN/Screen-Shot-2023-05-04-at-12-55-46-AM.png",
      },
    2: {
      id: 2,
      name: "New York",
      subtitle: "The Best Dining in NY",
      tags: [
        "Steak House",
        "speakeasy",
        "bar",
        "night",
        "club",
        "jazz",
        "bar",
        "fine dining",
      ],
      user: "Arielle",
      pfp: "https://i.ibb.co/FzpQcNT/33986-F7-C-DCA5-418-C-ACB9-917-CCB6-E5094.jpg",
      bookmarks: "32",
      photo: "https://i.ibb.co/XLZwrMC/new-york.png",
    },
    3: {
        id: 1,
        name: "San Francisco",
        subtitle: "My favorite resturaunts",
        tags: ["Chinese", "Moroccan", "Japanese", "Italian", "Tapas", "Wine bar"],
        user: "Marcel",
        pfp: "https://i.ibb.co/cDwSBHk/8-C5-BA17-C-326-E-4-C48-AE3-E-70-B3-D33-CE024.jpg",
        bookmarks: "15",
        photo: "https://i.ibb.co/sR6cvst/Screen-Shot-2023-05-03-at-9-16-24-PM.png",
      },
    };


export {DummyData2, DummyData3, DummyData4, DummyData5};
export default DummyData;
